---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pihole
  namespace: pihole-k8
spec:
  interval: 5m
  chart:
    spec:
      chart: pihole
      version: 2.4.0
      sourceRef:
        kind: HelmRepository
        name: pihole-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: pihole/pihole
      tag: v5.8.1
    virtualHost: "pihole-k8.${SECRET_DOMAIN}"
    DNS1: 10.0.3.24
    DNS2: 10.0.3.22
    serviceWeb:
      annotations:
        metallb.universe.tf/allow-shared-ip: pihole-svc
        metallb.universe.tf/address-pool: network-services
      type: LoadBalancer
    serviceDNS:
      annotations:
        metallb.universe.tf/allow-shared-ip: pihole-svc
        metallb.universe.tf/address-pool: network-services
      type: LoadBalancer
    ingress:
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-production"
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
      enabled: true
      hosts:
        - "pihole-k8.${SECRET_DOMAIN}"
      tls:
        - hosts:
            - "pihole-k8.${SECRET_DOMAIN}"
          secretName: "pihole-k8-tls"
    persistentVolumeClaim:
      enabled: true
      existingClaim: pihole-config
      size: 200mi
