---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plex
  namespace: media
spec:
  releaseName: plex
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: plex
      version: 6.0.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/plex
      tag: v1.24.4.5081-e362dc1ee
    podSecurityContext:
      # runAsUser: 23115
      # runAsGroup: 20513
      supplementalGroups:
        - 44
        - 109
        - 65539
        - 100

    env:
      TZ: "America/Denver"

    service:
      main:
        type: LoadBalancer
        loadBalancerIP: 10.0.3.162
        externalTrafficPolicy: Local

    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          # external-dns/is-public: "true"
          # external-dns.alpha.kubernetes.io/target: ingress.${DOMAIN_2}
          # external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
        hosts:
          - host: plex.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "plex.${SECRET_DOMAIN}"
            secretName: plex-tls

    persistence:
      config:
        enabled: true
        existingClaim: plex-pvc-config
      media:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: ${NAS_IP}
            path: /mnt/file_shares/media
        mountPath: /media
        readOnly: true
