---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-pv-media
spec:
  storageClassName: plex-nfs-media
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: ${NAS}
    path: /mnt/file_shares/media

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: media
  name: plex-pvc-media
spec:
  storageClassName: plex-nfs-media
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
