---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: media
  name: plex-pvc-media
spec:
  storageClassName: nfs-media
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
