---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-media
spec:
  storageClassName: nfs-media
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/file_shares/media
    server: ${NAS}
