---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-pvc-config
  namespace: adguard
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 128Mi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-pvc-data
  namespace: adguard
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 128Mi
