---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: adguard-home
  namespace: adguard
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: adguard-home
      version: 5.0.3
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    imagePullSecrets:
      - name: regcred
    image:
      repository: adguard/adguardhome
      tag: v0.106.3
      pullPolicy: Always
    persistence:
      enabled: true
      existingClaim: pihole-config
      size: 200mi
    env:
      TZ: "America/Denver"
      PUID: "1000"
      PGID: "1000"
    service:
      main:
        port:
          port: 3000
      dns-tcp:
        enabled: true
        type: LoadBalancer
        externalIPs:
          - 10.0.3.160
        externalTrafficPolicy: Local
        port:
          port: 53
          name: dns-tcp
          protocol: TCP
          targetPort: 53

      dns-udp:
        enabled: true
        nameSuffix: dns-udp
        type: LoadBalancer
        externalIPs:
          - 10.0.3.160
        externalTrafficPolicy: Local
        port:
          port: 53
          name: dns-udp
          protocol: UDP
          targetPort: 53

    ingress:
      main:
        enabled: true
        # ingressClassName: "nginx-internal"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - host: "adguard.${SECRET_DOMAIN}"
        tls:
          - hosts:
              - "adguard.${SECRET_DOMAIN}"
            secretName: adguard-tls
    resources:
      requests:
        memory: 1000Mi
        cpu: 200m
      limits:
        memory: 2000Mi
