---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: adguard-pv-config
spec:
  storageClassName: adguard-nfs-config
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: ${NAS}
    path: /mnt/file_shares/k8_apps/adguard/config

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: adguard
  name: adguard-pvc-config
spec:
  storageClassName: adguard-nfs-config
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
